/*
 * Copyright (C) 2008 by Steve Krulewitz <skrulx@gmail.com>
 * Licensed under GPLv2 or later, see file LICENSE in the xpi for details.
 */
#include "nsISupports.idl"

interface nsIArray;
interface nsIURI;

[scriptable, uuid(86371189-7842-45b1-b9b1-96041c3cb7bf)]
interface gfISearchResult : nsISupports
{
  readonly attribute unsigned long long scriptId;
  readonly attribute unsigned long match;
  readonly attribute AString name;
  readonly attribute unsigned long installs;
  readonly attribute unsigned long long updated;
  readonly attribute float rank;
};

[scriptable, uuid(ba0e6958-343c-490c-b228-bcc1214b282b)]
interface gfIGreasefireService : nsISupports
{
  void startup();
  void shutdown();

  readonly attribute unsigned long long indexDate;
  readonly attribute unsigned long scriptCount;

  boolean hasScripts(in nsIURI aURL);
  nsIArray search(in nsIURI aURL);
};
